### PR TITLE
php 8.1 support null check for string func

### PR DESCRIPTION
**Pull request by paveurba**

### CODE REVIEW

**Comment by sayid** [comment]
您好，我已经收到您的信件，将尽快回复您。

**Comment by snehalSG90** [comment]
I am facing issue with PHP 8.1 on same line. Could we please have it in the master branch?

**Comment by pamoller** [comment]
> I am facing issue with PHP 8.1 on same line. Could we please have it in the master branch?

Yes, it would be very nice. PHP 8.1 becomes the next minor version of PHP for my clients provider.

**Review by teson2000 — COMMENTED** [review]
Better to instist that function should always return string, so:
764: if (is_null($val)) return '';

**Comment by mk-j** [comment]
This has been fixed in master.

**Pull request closed without merging**
