### PR TITLE
Allow to update column format 

### PR DESCRIPTION
**Pull request by Shnoulle**
https://github.com/mk-j/PHP_XLSXWriter/issues/124

To have different table with different format in same sheet

### CODE REVIEW

**Comment by Shnoulle** [comment]
See https://github.com/mk-j/PHP_XLSXWriter/issues/128#issuecomment-324417537 this allow to have each line with different format if needed.

**Comment by Shnoulle** [comment]
Can be easily updated to https://github.com/mk-j/PHP_XLSXWriter/commits/2017-09-0.36-r1

**Comment by mddo13** [comment]
Hi,

I really need this functionality for my work project.
Is this method scheduled for integration soon?

Thanks.

**Comment by Shnoulle** [comment]
I use my fork on a private tool.

**Comment by Shnoulle** [comment]
@mk-j : sorry, i don't follow since month now. Implemented or need a better fix ?

**Comment by Shnoulle** [comment]
OK ; https://github.com/mk-j/PHP_XLSXWriter/issues/124#issuecomment-1571056443

Thanks

**Pull request closed without merging**
