### PR TITLE
Add new functional (add empty line & count sheet rows)

### PR DESCRIPTION
**Pull request by yurybykov**

### CODE REVIEW

**Comment by mk-j** [comment]
Looks good so far, I just need to get some time to look this over a bit further.

**Comment by mk-j** [comment]
I actually merged most of the commits into the 2017-07-0.35-rc1 branch.  I'm holding off on 81086e5.  Does the current implementation of xmlspecialchars() corrupt cyrillic UTF8 or something?

**Comment by yurybykov** [comment]
No, it is not corrupt. In my case I need to save \n\r\t symbols to have few lines in one ceil.

**Comment by mk-j** [comment]
I thought someone had a "Excel finds unreadable content in file... do you want to recover contents of this workbook" issue with \r\n\t, maybe not... I might add those back in an upcoming release, i'll think about it.  Thanks.

**Comment by mk-j** [comment]
Just a heads up.  Someone else requested allowing \r\n\t into the cell strings as well, so that is now available in mk-j:2017-07-0.35-rc1

**Pull request closed without merging**
