### PR TITLE
Hyperlinks Support Added

### PR DESCRIPTION
**Pull request by mayank**
Added Support for adding Hyperlinks to the Cells using a separate array to be passed when `writeSheet()` is called.
You can see example for more details.

### CODE REVIEW

**Comment by mayank** [comment]
@mk-j not merged yet, any issue? :confused:

**Comment by mk-j** [comment]
The last big release was in january, i'm not ready to add this in yet, but perhaps the next release.

**Comment by pathfindercb** [comment]
Hope you'll consider #105 in the next release. Let me know if you have any questions.

**Comment by nitrag** [comment]
+1

**Comment by premax** [comment]
+1

**Comment by slououou** [comment]
Seems not work for excel 2016. The link is gone after being forced recovered while other data remains. Is there's a way to make those code work for it?

**Comment by mayank** [comment]
@slououou share a sample file!

**Comment by slououou** [comment]
example.xlsx is the file generated with the code while example_changed.xlsx is the file  "repaired"  by the ms excel 2016.
[example_changed.xlsx](https://github.com/mk-j/PHP_XLSXWriter/files/1618638/example_changed.xlsx)
[example.xlsx](https://github.com/mk-j/PHP_XLSXWriter/files/1618623/example.xlsx)
The repaire info is:`<?xml version="1.0" encoding="UTF-8" standalone="true"?>
-<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
<logFileName>error171880_01.xml</logFileName>
<summary>Errors were detected in file 'C:\Users\someone\Desktop\example.xlsx'</summary>
-<additionalInfo>
<info>Excel completed file level validation and repair. Some parts of this workbook may have been repaired or discarded.</info>
</additionalInfo>
</recoveryLog>`

**Comment by mayank** [comment]
@slououou repaired file works well?

**Comment by slououou** [comment]
No, I checked the content of the files, the rels is removed after repaired, but I need them for the hyperlink.

**Comment by slououou** [comment]
This "forced repair" can be avoided by adding:
`<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>`
into [Content_Types].xml.
But still, the hyperlink is not shown in the cell.

**Comment by bartmika** [comment]
+1

@mk-j @mayank What is the status of this merge request?

**Comment by epandzo** [comment]
Hi,

There is a simple workaround for adding hyperlinks. Excel supports HYPERLINK as a formula, so example would be something like this:

```
<?php
include_once("xlsxwriter.class.php");

$filename = "example.xlsx";
$rows = array(
    array('2003','TEST', '=HYPERLINK("HTTP://WWW.GOOGLE.COM", "GOOGLE")'),
);

$writer = new XLSXWriter();
foreach($rows as $row)
	$writer->writeSheetRow('Sheet1', $row);

$writer->writeToFile('example.xlsx');

?>
```

**Comment by BIERAAP** [comment]
> $writer->writeSheetRow('Sheet1', $row);

To bad the links are working on an laptop or android phone but not iPhone ;(

**Comment by Somnium7** [comment]
> @mayank This "forced repair" can be avoided by adding:
> `<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>`
> into [Content_Types].xml.
> But still, the hyperlink is not shown in the cell.

Regarding broken Excel file, see @slououou comment and <hyperlinks> section should go just before <printOptions>.

**Comment by JulioPradera** [comment]
Hello there.
Was there any update regarding the problem with the links? Even the example file doesn't seem to be working.

**Pull request closed without merging**
